apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-backend
  template:
    metadata:
      labels:
        app: expense-backend
    spec:
      containers:
        - name: backend
          image: kushagrashri/expense-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "expense_tracker"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: expense-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007